---
default_language_version:
  node: lts
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.2
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                .*\.md$|
                .*\.ascii$|
                .*\.ref$|
                .*\.diff$|
                .*\.rtf$|
                .*\.svg$
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
                .*\.ascii$|
                .*\.ref$|
                .*\.diff$|
                .*\.rtf$|
                .*\.svg$
          )
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.0"
    hooks:
      - id: biome-check
      - id: biome-lint
      - id: biome-format
      - id: biome-ci
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        exclude_types:
          - jupyter
          - json
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  # - repo: https://github.com/editorconfig-checker/editorconfig-checker
  #   rev: v3.4.1
  #   hooks:
  #     - id: editorconfig-checker
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.5
    hooks:
      - id: uv-lock
      - id: uv-export
